import {test,expect} from '@playwright/test';
test('phone armory exposes locks, unlocks and distinct weapons',async({browser})=>{
 const c=await browser.newContext({viewport:{width:320,height:568},hasTouch:true,isMobile:true});const p=await c.newPage();await p.goto('/?e2e');await p.getByRole('button',{name:'DEPLOY'}).tap();await p.locator('#weapon').tap();await expect(p.locator('[data-weapon="2"]')).toBeDisabled();await expect(p.locator('[data-weapon="3"]')).toContainText('Clear Homeward');
 const box=(await p.locator('#weapon-picker').boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(320);await p.screenshot({path:'test-results/armory-locked-phone.png'});
 await p.evaluate(()=>{const g=(window as any).__steel;g.save.cleared[0]=true;g.updateHud();});await p.locator('[data-weapon="2"]').tap();await expect(p.locator('#weapon-picker')).toBeHidden();expect(await p.evaluate(()=>(window as any).__steel.weapon)).toBe(1);
 await p.evaluate(()=>{const g=(window as any).__steel;g.save.cleared[1]=true;g.save.cleared[2]=true;g.updateHud();});await p.locator('#weapon').tap();await p.locator('[data-weapon="3"]').tap();expect(await p.evaluate(()=>(window as any).__steel.weapon)).toBe(2);
 const weapons=await p.evaluate(()=>{const g=(window as any).__steel;return [0,1,2].map(w=>{g.weapon=w;const stats=g.weaponStats();g.shoot(g.player,true);return {...stats,color:g.shots.at(-1).mesh.material.color.getHex()};});});expect(new Set(weapons.map(w=>w.color)).size).toBe(3);expect(weapons[1].reload).toBeLessThan(weapons[0].reload);expect(weapons[2].splash).toBeGreaterThan(0);
 await p.locator('#weapon').tap();await p.screenshot({path:'test-results/armory-unlocked-phone.png'});await c.close();
});
test('ring barrage hits surrounding enemies while keeping the call position clear',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const result=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.world.covers=[];g.world.activities=[];g.world.navigationRevision++;g.enemies=[];g.player.visual.root.position.set(0,0,0);g.aimPoint.set(60,0,50);g.callArtillery();const positions=g.strikes.map((s:any)=>({x:s.x,z:s.z,r:s.marker.geometry.parameters.outerRadius}));const inside=g.makeUnit(0,18,'heavy'),outside=g.makeUnit(0,30,'heavy');inside.visual.root.position.set(0,0,18);outside.visual.root.position.set(0,0,30);inside.hp=outside.hp=10000;g.enemies=[inside,outside];const hp=g.player.hp;g.updateActivities(2.5);return {positions,hit:inside.hp<10000,safe:outside.hp===10000&&g.player.hp===hp,clean:g.strikes.length===0&&g.barrageZones.length===0};});expect(result.positions).toHaveLength(12);expect(result.positions.every((p:any)=>p.r===8&&Math.abs(Math.hypot(p.x,p.z)-18)<.001)).toBe(true);expect(result.hit&&result.safe&&result.clean).toBe(true);
});
