import {test,expect,type Page} from '@playwright/test';
import {freshSave,parseSave,encounterSize,SAVE_KEY,levelMission} from '../src/three/campaign';
async function arena(page:Page){await page.goto('/?e2e');await expect(page.getByRole('button',{name:'DEPLOY'})).toBeVisible();await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};});}
test('old checkpoints keep all campaign indices; training is separate and Easy grows gradually',()=>{
 const s=freshSave();s.mission=5;s.level=2;s.credits=500;s.cleared=s.cleared.map((_,i)=>i<5);delete s.training;const restored=parseSave(JSON.stringify(s));expect(restored.mission).toBe(5);expect(restored.level).toBe(2);expect(restored.training?.skipped).toBe(true);expect(restored.credits).toBe(500);expect(encounterSize(0,0,'easy')).toMatchObject({armor:2,riflemen:4,rocketeers:0,jeeps:0});expect(levelMission(13,1).kind).toBe('rescue');expect(levelMission(13,0).kind).toBe('assault');expect(levelMission(13,2).kind).toBe('boss');
});
test('training maps, lesson gates, boundaries and temporary supplies never alter campaign inventory',async({page})=>{
 await arena(page);const r=await page.evaluate(async()=>{const g=(window as any).__steel;g.save.strikeCharges=9;g.save.autoPack=6;g.save.weapons=[3,4,8];const before=JSON.stringify(g.save),rows=[];
  for(let id=0;id<3;id++){g.startTraining(id);const counts={rifles:g.enemies.filter((e:any)=>e.role==='rifleman').length,tanks:g.enemies.filter((e:any)=>!g.isInfantry(e)).length};g.updateEnemies(.1);const sleeping=g.enemies.every((e:any)=>!e.encounter.active);await g.persist();const stored=localStorage.getItem('steel-front-3d-v1');const p=g.player.visual.root.position;for(let n=0;n<250;n++)g.moveUnit(g.player,2,0,.1);rows.push({id,counts,sleeping,bounds:{...g.world.bounds},inside:p.x<g.world.bounds.x,saved:stored===before});g.leaveTraining();}
 return {rows,unchanged:JSON.stringify(g.save)===before};});expect(r.unchanged).toBe(true);expect(r.rows.map(r=>r.counts)).toEqual([{rifles:3,tanks:0},{rifles:4,tanks:2},{rifles:4,tanks:2}]);expect(r.rows.map(r=>r.bounds)).toEqual([{x:16,z:24},{x:26,z:16},{x:22,z:20}]);for(const row of r.rows)expect(row.sleeping&&row.inside&&row.saved).toBe(true);
});
test('training only awards once, cannot end before lessons and exit, and never records ranking',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.startTraining(0);for(const e of g.enemies)e.dead=true;const gated=g.objectiveProgress()===0;g.training.moved=true;g.shotsFired=1;g.player.visual.root.position.set(0,0,-18);g.step(.02);const finish=g.phase==='finishing',credits=g.campaignSave.credits;g.step(1.5);const result=g.overlay.textContent;g.startTraining(0);g.training.moved=true;g.shotsFired=1;for(const e of g.enemies)e.dead=true;g.player.visual.root.position.set(0,0,-18);g.step(.02);return {gated,finish,result,credits,again:g.campaignSave.credits,rank:localStorage.getItem('steel-front-leaderboard-v1')};});expect(r.gated&&r.finish).toBe(true);expect(r.result).toContain('Lesson complete');expect(r.credits).toBe(10);expect(r.again).toBe(10);expect(r.rank).toBeNull();
});
test('weapon lesson requires collecting and selecting; support lesson uses successful actions',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.startTraining(1);const a=g.world.activities.find((a:any)=>a.kind==='laser');g.player.visual.root.position.set(a.x,0,a.z);g.updateActivities(.02);g.training.update(g);g.action('4');const weapon=g.training.collected&&g.training.switched&&g.weapon===3;g.startTraining(2);g.shoot(g.player,true);const locked=g.shots.length===0;g.action('shield');g.action('support-strike');g.training.update(g);return {weapon,locked,shield:g.training.shielded,strike:g.training.struck,active:g.enemies.some((e:any)=>e.encounter.active),stock:g.campaignSave.strikeCharges};});expect(r).toEqual({weapon:true,locked:true,shield:true,strike:true,active:true,stock:0});
});
test('defense starts beside relay, reserves do not fight, and countdown matches release',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(3,0);const near=Math.hypot(g.player.visual.root.position.x,g.player.visual.root.position.z+13),allPending=g.enemies.every((e:any)=>e.pending);g.elapsed=6.9;g.updateEnemies(.01);const grace=g.enemies.every((e:any)=>e.pending);g.elapsed=7;g.updateEnemies(.01);const wave=g.waves.wave,active=g.enemies.filter((e:any)=>!e.pending);for(const e of active)g.damageUnit(e,1e6,g.player.visual.root.position);g.waves.update(g);const next=g.waves.nextAt,clear=g.battlefieldClear();g.elapsed=next-.1;g.waves.update(g);const waiting=g.waves.wave===0;g.elapsed=next;g.waves.update(g);return {near,allPending,grace,wave,clear,waiting,nextWave:g.waves.wave,text:g.waves.text(g)};});expect(r.near).toBeLessThanOrEqual(5);expect(r.allPending&&r.grace&&r.waiting).toBe(true);expect(r.wave).toBe(0);expect(r.clear).toBe(false);expect(r.nextWave).toBe(1);expect(r.text).toContain('WAVE 2/4');
});
test('transport guns change by level and fire without spending player inventory',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel,rows=[];for(let lv=0;lv<3;lv++){g.start(2,lv);g.world.covers=[];g.enemies.forEach((e:any)=>e.dead=true);const p=g.convoy.position,e=g.makeUnit(p.x+10,p.z,'raider');e.encounter={active:true,group:0};g.enemies=[e];const ammo=g.specialAmmo.join(),stock=g.save.strikeCharges;g.allies.cooldown=0;g.allies.update(g,.02);rows.push({lv,gun:!!g.allies.gun,shots:g.shots.length,damage:g.shots[0]?.damage??0,independent:ammo===g.specialAmmo.join()&&stock===g.save.strikeCharges,safe:g.shots[0]?.alliedSafe??true});}return rows;});expect(r.map(x=>x.gun)).toEqual([true,true,false]);expect(r.map(x=>x.damage)).toEqual([60,3,0]);expect(r.every(x=>x.independent&&x.safe)).toBe(true);
});
test('rescue is contested, cannot skip unrescued tanks, allies survive hostile fire and never drop loot',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(13,1);const first=g.allies.tanks[0],second=g.allies.tanks[1];const visible=first.unit.visual.root.children.length>0;let meshesVisible=false;first.unit.visual.root.traverse((o:any)=>{if(o.isMesh&&o.userData.modelAsset&&o.layers.mask&1)meshesVisible=true;});for(const e of g.enemies)e.dead=true;const gated=g.objectiveProgress()<1;
  const p=first.unit.visual.root.position;g.player.visual.root.position.set(p.x+3,0,p.z);const guard=g.makeUnit(p.x+7,p.z,'rifleman');g.enemies.push(guard);g.allies.update(g,3);const contested=!first.rescued;guard.dead=true;g.allies.update(g,3);g.player.visual.root.position.copy(second.unit.visual.root.position).add({x:3,y:0,z:0});g.allies.update(g,3);const rescued=g.allies.saved===2,done=g.objectiveProgress()===1,kills=g.kills,loot=g.salvageDrops;g.shieldTime=0;g.damageUnit(first.unit,1e6,p);const survivor=g.objectiveProgress()===1;g.damageUnit(second.unit,1e6,p);g.step(.02);return {visible:visible&&meshesVisible,gated,contested,rescued,done,survivor,failed:g.phase==='failed',noLoot:g.kills===kills&&g.salvageDrops===loot};});expect(Object.values(r).every(Boolean),JSON.stringify(r)).toBe(true);
});
test('allied shell hits a hostile but direct splash spares friendly units; following clears cover',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(13,1);g.world.covers=[];g.world.navigationRevision++;g.enemies=[];const a=g.allies.tanks[0];a.rescued=true;a.unit.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,18);const e=g.makeUnit(0,8,'raider');g.enemies=[e];a.unit.aim=0;g.syncVisual(a.unit);const hp=e.hp,own=a.unit.hp,player=g.player.hp;g.allyRound(a.unit.visual.root.position,0,60,30,2.5,a.unit.visual.muzzle,true);for(let i=0;i<60;i++)g.updateShots(1/60);const hit=e.hp<hp,safe=a.unit.hp===own&&g.player.hp===player;
  e.dead=true;g.allies.trail=[{x:0,z:12},{x:0,z:18}];for(let i=0;i<120;i++)g.allies.update(g,1/30);return {hit,safe,followed:a.unit.visual.root.position.z>4};});expect(r).toEqual({hit:true,safe:true,followed:true});
});
for(const viewport of [{width:390,height:844},{width:844,height:390}])test(`mobile training ${viewport.width}: controls and hint remain usable`,async({browser})=>{
 const context=await browser.newContext({viewport,isMobile:true,hasTouch:true});const page=await context.newPage();await arena(page);await page.getByRole('button',{name:'START TRAINING'}).click();await page.evaluate(()=>{const g=(window as any).__steel;g.updateHud();g.world.update(0,g.player.visual.root.position);});await expect(page.locator('#lesson-hint')).toBeVisible();await expect(page.locator('#move-pad')).toBeVisible();const r=await page.evaluate(()=>{const hint=document.querySelector('#lesson-hint')!.getBoundingClientRect(),pad=document.querySelector('#move-pad')!.getBoundingClientRect();return {width:document.documentElement.scrollWidth,clear:hint.bottom<pad.top||hint.left>pad.right};});expect(r.width).toBeLessThanOrEqual(viewport.width);expect(r.clear).toBe(true);await page.screenshot({path:`test-results/training-${viewport.width}.png`});await context.close();
});

for(const viewport of [{width:360,height:640},{width:667,height:375},{width:320,height:568}])test(`small phone ${viewport.width}: lesson hints guide each tap and never cover controls`,async({browser})=>{
 const context=await browser.newContext({viewport,isMobile:true,hasTouch:true});const page=await context.newPage();await arena(page);
 // Any visible hint must stay clear of the mission card, the gun list and the uplink label.
 const clear=()=>page.evaluate(()=>{const g=(window as any).__steel;g.updateHud();g.projectRelay();const hint=document.querySelector('#lesson-hint') as HTMLElement;if(hint.hidden||getComputedStyle(hint).visibility==='hidden')return [];const h=hint.getBoundingClientRect();
  return ['.mission-hud','#weapon-picker','#relay-label','#move-pad','#aim-pad'].filter(s=>{const e=document.querySelector(s) as HTMLElement|null;if(!e||e.hidden||e.closest('[hidden]'))return false;const b=e.getBoundingClientRect();return Math.min(h.right,b.right)-Math.max(h.left,b.left)>2&&Math.min(h.bottom,b.bottom)-Math.max(h.top,b.top)>2;});});
 await page.evaluate(()=>{const g=(window as any).__steel;g.startTraining(1);g.training.moved=true;const a=g.world.activities.find((a:any)=>a.kind==='laser');g.player.visual.root.position.set(a.mesh.position.x,0,a.mesh.position.z);g.updateActivities(.01);g.training.update(g);g.updateHud();});
 await expect(page.locator('#weapon')).toHaveClass(/lesson-target/);expect(await clear()).toEqual([]);
 await page.locator('#weapon').tap();await page.evaluate(()=>(window as any).__steel.updateHud());
 const laser=page.locator('#weapon-picker [data-weapon="4"]');await expect(laser).toHaveClass(/lesson-target/);await expect(page.locator('#lesson-hint')).toContainText('LASER');expect(await clear()).toEqual([]);
 await laser.tap();expect(await page.evaluate(()=>{const g=(window as any).__steel;return g.training.switched&&g.weapon===3&&!g.weaponPickerOpen;})).toBe(true);
 await page.evaluate(()=>{const g=(window as any).__steel;g.startTraining(2);g.updateHud();});await expect(page.locator('#shield')).toHaveClass(/lesson-target/);expect(await clear()).toEqual([]);
 await page.locator('#shield').tap();expect(await page.evaluate(()=>(window as any).__steel.training.shielded)).toBe(true);await context.close();
});

test('Easy First Light splits its small arena into two encounters',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(0,0);g.updateEnemies(.01);const groups=[...new Set(g.enemies.map((e:any)=>e.encounter.group))],later=g.enemies.filter((e:any)=>e.encounter.group===1),waiting=later.every((e:any)=>!e.encounter.active);for(const e of g.enemies)if(e.encounter.group===0)e.dead=true;g.player.visual.root.position.set(0,0,-5);g.elapsed=1;g.updateEnemies(.01);return {groups,waiting,released:later.some((e:any)=>e.encounter.active)};});expect(r).toEqual({groups:[0,1],waiting:true,released:true});
});
test('allied supports pause, preserve idle ambushes and keep resources bounded across retries',async({page})=>{
 await arena(page);const r=await page.evaluate(async()=>{const g=(window as any).__steel;g.start(2,0);g.world.covers=[];g.world.navigationRevision++;g.enemies=[];const p=g.convoy.position,e=g.makeUnit(p.x+10,p.z,'raider');e.encounter={group:0,active:false,anchor:{x:0,z:0},meters:0};g.enemies=[e];g.allies.cooldown=0;g.allies.update(g,.01);const idle=g.shots.length===0;g.pause();e.encounter.active=true;g.allies.update(g,10);const paused=g.shots.length===0;g.resume();g.elapsed+=.2;g.allies.update(g,.01);const fired=g.shots.length===1&&g.shots[0].homing===e;
  await g.world.load(true);g.world.settings(true);const memory=[];for(let run=0;run<4;run++){g.start(13,1);g.allies.tanks.forEach((a:any)=>a.rescued=true);for(const e of g.enemies)e.cooldown=1e6;g.player.hp=1e9;for(let frame=0;frame<300;frame++){g.elapsed+=1/30;g.allies.update(g,1/30);g.updateShots(1/30);g.world.fx.update(1/30,g.world.camera);}g.world.update(0,g.player.visual.root.position);memory.push(g.world.renderer.info.memory.geometries);}return {idle,paused,fired,memory,trail:g.allies.trail.length,shots:g.shots.length};});expect(r.idle&&r.paused&&r.fired).toBe(true);expect(r.memory.at(-1)!).toBeLessThanOrEqual(r.memory[0]+30);expect(r.trail).toBeLessThanOrEqual(96);expect(r.shots).toBeLessThan(15);
});

test('training Strike cannot hit a future wave before it is released',async({page})=>{
 await arena(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.startTraining(2);const later=g.enemies.filter((e:any)=>e.encounter.group===1),before=later.map((e:any)=>e.hp);g.action('shield');g.action('support-strike');const onlyFirst=g.strikes.length>0&&g.strikes.every((s:any)=>s.target.encounter.group===0);g.guided.update(g,5);const untouched=later.every((e:any,i:number)=>e.hp===before[i]&&e.pending&&!e.visual.root.visible);for(const e of g.enemies.filter((e:any)=>e.encounter.group===0))e.dead=true;g.training.update(g);return {onlyFirst,untouched,released:later.every((e:any)=>!e.pending&&e.encounter.active&&e.visual.root.visible),unfinished:g.objectiveProgress()<1};});expect(Object.values(r).every(Boolean),JSON.stringify(r)).toBe(true);
});
