import {test,expect} from '@playwright/test';
test('three boss models have telegraphed attacks, weak cores and cleanup',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;const results=[];
 for(const mission of [5,6,8]){g.start(mission,2);const b=g.enemies.find((e:any)=>e.role==='boss');for(const e of g.enemies)if(e!==b)e.dead=true;b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,30);g.bosses.update(g,b,4.1);const s=g.bosses.states.get(b);const warned=s.phase==='charging';const markers=s.markers.length,locked=JSON.stringify(s.targets);g.player.visual.root.position.set(35,0,30);const hp=g.player.hp;g.bosses.update(g,b,2.1);const dodged=g.player.hp===hp,exposed=g.bosses.multiplier(b)>1&&b.visual.root.getObjectByName('Core').visible,shots=g.shots.length;
 const initial=b.hp;g.damageUnit(b,20,g.player.visual.root.position);const weak=initial-b.hp;b.hp=initial;s.phase='tracking';g.damageUnit(b,20,g.player.visual.root.position);const armor=initial-b.hp;const model=b.visual.root.userData.model;g.start(0);results.push({mission,model,warned,markers,dodged,exposed,shots,stronger:weak>armor,clean:g.bosses.states.size===0});}
 return results;});expect(r.map((v:any)=>v.model)).toEqual(['boss-rail','boss-missile','boss-walker']);for(const row of r){expect(row.warned&&row.dodged&&row.exposed&&row.stronger&&row.clean,JSON.stringify(row)).toBe(true);}expect(r[1].markers).toBe(3);expect(r[2].shots).toBe(3);
});
test('rail cover protection and destruction cancels pending missile zones',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(5,2);let b=g.enemies.find((u:any)=>u.role==='boss');const wall=g.world.covers[0];g.world.covers=[wall];b.visual.root.position.set(wall.x,0,wall.z-8);g.player.visual.root.position.set(wall.x,0,wall.z+8);const hp=g.player.hp;g.bosses.rail(g,b,0);const protectedByCover=hp===g.player.hp;wall.hp=0;g.bosses.rail(g,b,0);const openHit=hp>g.player.hp;g.start(6,2);b=g.enemies.find((u:any)=>u.role==='boss');b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,30);g.bosses.update(g,b,4.1);const markers=[...g.bosses.states.get(b).markers];g.damageUnit(b,99999,g.player.visual.root.position);return {protectedByCover,openHit,cancelled:markers.length===3&&markers.every((m:any)=>!m.parent)&&!g.bosses.states.has(b),wreckModel:g.world.wrecks[0].root.getObjectByName('boss-missile')!==undefined};});expect(r).toEqual({protectedByCover:true,openHit:true,cancelled:true,wreckModel:true});
});
test('boss encounter screenshots and compact mobile readout',async({browser})=>{
 const c=await browser.newContext({viewport:{width:1000,height:700}});const p=await c.newPage();await p.goto('/?e2e');await p.getByRole('button',{name:'DEPLOY'}).click();for(const [mission,name] of [[5,'rail'],[6,'missile'],[8,'walker']] as const){await p.evaluate(i=>{const g=(window as any).__steel;g.start(i,2);g.frame=()=>{};const boss=g.enemies.find((u:any)=>u.role==='boss');boss.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,15);g.world.update(0,g.player.visual.root.position);g.world.camera.position.set(12,16,25);g.world.camera.lookAt(0,0,2);g.world.renderer.render(g.world.scene,g.world.camera);g.updateHud();},mission);await p.screenshot({path:`test-results/boss-${name}.png`});}
 await p.setViewportSize({width:320,height:568});await p.evaluate(()=>{const g=(window as any).__steel;g.start(8,2);g.updateHud();});await expect(p.locator('#boss-readout')).toContainText('Iron Sovereign');const spacing=await p.evaluate(()=>({bottom:document.querySelector('.mission-hud')!.getBoundingClientRect().bottom,top:document.querySelector('#radio')!.getBoundingClientRect().top}));expect(spacing.top).toBeGreaterThan(spacing.bottom);await c.close();
});
