import {test,expect} from '@playwright/test';
test('tank weapon salvage drops once and is collected once without buying ownership',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.start(4);const rolls=[.9,.9,.9,.1,.6];g.lootRandom=()=>rolls.shift()??.9;const original=g.world.activities.length;const tanks=g.enemies.filter((u:any)=>!g.isInfantry(u)&&u.role!=='jeep');for(const u of tanks.slice(0,4))g.damageUnit(u,9999,g.player.visual.root.position);const drop=g.world.activities.at(-1);g.damageUnit(tanks[1],9999,g.player.visual.root.position);const once=g.world.activities.length===original+1;g.player.visual.root.position.set(drop.x,0,drop.z);g.updateActivities(.01);const ammo=g.specialAmmo[0];g.updateActivities(.01);return {once,kind:drop.kind,spent:drop.spent,ammo,same:ammo===g.specialAmmo[0],owned:g.save.weapons.includes(3)};});expect(r).toEqual({once:true,kind:'laser',spent:true,ammo:6,same:true,owned:false});
});
test('defense enemies approach from corners and give the player time to protect the relay',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(3);g.frame=()=>{};const dist=(u:any)=>Math.hypot(u.visual.root.position.x,u.visual.root.position.z+13);const initial=g.enemies.map(dist);const nearby=Math.hypot(g.player.visual.root.position.x,g.player.visual.root.position.z+13);for(let i=0;i<360;i++)g.step(1/60);const moved=g.enemies.some((u:any,i:number)=>dist(u)<initial[i]-3);const health=g.relayHealth;for(const u of g.enemies)u.dead=true;g.spawnTimer=12;g.step(.1);return {initial,nearby,moved,health,reinforcement:dist(g.enemies.at(-1))};});expect(Math.min(...r.initial)).toBeGreaterThan(40);expect(r.nearby).toBeLessThan(12);expect(r.moved).toBe(true);expect(r.health).toBe(300);expect(r.reinforcement).toBeGreaterThan(40);
});
test('keyboard aiming, fire, strike and abilities work without mouse aiming',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.player.hp-=120;g.auto.ammo=6;g.updateHud();});await page.keyboard.down('l');await page.keyboard.down('f');await page.evaluate(()=>(window as any).__steel.updatePlayer(.4));await page.keyboard.up('f');await page.keyboard.up('l');const r=await page.evaluate(()=>{const g=(window as any).__steel;return {shots:g.shotsFired,east:g.aimPoint.x>g.player.visual.root.position.x,mouse:g.input.hasMouse};});expect(r).toEqual({shots:1,east:true,mouse:false});await page.keyboard.press('r');await page.keyboard.press('q');await page.keyboard.press('e');expect(await page.evaluate(()=>{const g=(window as any).__steel;return g.strikes.length>0&&g.shieldTime>0&&g.auto.ammo===5&&g.auto.guided.strikes.length===1&&g.radio.textContent.includes('AUTO');})).toBe(true);await page.evaluate(()=>(window as any).__steel.reload=0);await page.locator('#fire').click();expect(await page.evaluate(()=>(window as any).__steel.shotsFired)).toBe(2);await page.keyboard.press('Escape');await page.keyboard.down('f');expect(await page.evaluate(()=>(window as any).__steel.input.keys.size)).toBe(0);await page.keyboard.up('f');
});
