import {test,expect} from '@playwright/test';
test('material effects, burning cleanup and low-mode limits survive chain destruction',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel,fx=g.world.fx;g.frame=()=>{};fx.clear();const stone=g.world.covers.find((c:any)=>c.kind==='stonewall');g.hitCover(stone,999);const masonry=fx.fires.length===0&&fx.particles.some((p:any)=>p.kind==='smoke');const wood=g.world.covers.find((c:any)=>c.kind==='pine');g.hitCover(wood,999);const fire=fx.fires.length===1;g.hitCover(wood,999);const once=fx.fires.length===1;for(let i=0;i<20;i++)fx.surface(wood.mesh.position,'fuel',true);const bounded=fx.fires.length<=6&&fx.particles.length<=230;fx.clear();fx.low=true;for(let i=0;i<20;i++)fx.surface(wood.mesh.position,'fuel',true);const low=fx.fires.length<=2&&fx.particles.length<=85;fx.update(20,g.world.camera);const expired=fx.fires.length===0&&fx.particles.length===0;fx.surface(wood.mesh.position,'wood',true);g.start(0);return {masonry,fire,once,bounded,low,expired,reset:fx.fires.length===0&&fx.particles.length===0};});expect(r).toEqual({masonry:true,fire:true,once:true,bounded:true,low:true,expired:true,reset:true});
});

test('burning cover remains readable in both graphics modes',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();await page.evaluate(()=>(window as any).__steel.frame=()=>{});
 for(const low of [false,true]){const count=await page.evaluate(low=>{const g=(window as any).__steel;g.start(0);g.world.settings(low);const c=g.world.covers.find((c:any)=>c.kind==='fuelcrate');g.world.camera.position.set(c.x+8,18,c.z+22);g.world.camera.lookAt(c.x,0,c.z);g.world.camera.updateMatrixWorld();g.hitCover(c,999);for(let i=0;i<3;i++)g.world.fx.update(.15,g.world.camera);g.world.renderer.render(g.world.scene,g.world.camera);g.hud.hidden=true;return g.world.fx.particles.length;},low);expect(count).toBeLessThanOrEqual(low?85:230);await page.screenshot({path:`test-results/burning-cover-${low?'low':'high'}.png`});}
});
