import {test,expect} from '@playwright/test';

test('two helicopter bosses reserve separate landing zones',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const result=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.save.difficulty='crazy';g.start(2,2);g.enemies=g.enemies.filter((u:any)=>u.bossKind==='helicopter');g.world.covers=[{x:0,z:10,w:6,d:2,hp:Infinity,kind:'barricade'}];g.player.visual.root.position.set(0,0,28);g.enemies[0].visual.root.position.set(-12,0,-10);g.enemies[1].visual.root.position.set(12,0,-10);for(const b of g.enemies)g.bosses.update(g,b,.1);const [a,b]=g.enemies.map((u:any)=>g.bosses.states.get(u).landing);return {count:g.enemies.length,separation:Math.hypot(a.x-b.x,a.z-b.z)};});expect(result.count).toBe(2);expect(result.separation).toBeGreaterThan(6);
});
test('helicopter abandons a stale waypoint and follows a distant player',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const distance=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.start(2,2);const b=g.enemies.find((u:any)=>u.role==='boss');g.enemies=[b];g.world.covers=[];b.visual.root.position.set(0,6,-40);g.player.visual.root.position.set(0,0,50);g.bosses.update(g,b,.01);g.bosses.states.get(b).landing={x:0,z:-40};for(let i=0;i<100;i++)g.bosses.update(g,b,.05);return Math.hypot(b.visual.root.position.x,b.visual.root.position.z-50);});expect(distance).toBeLessThan(80);
});
test('spider seeks clear footing before resting in dense cover',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const rested=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.start(12,2);const b=g.enemies.find((u:any)=>u.role==='boss');g.enemies=[b];g.world.covers=[];for(let x=-28;x<=28;x+=4.8)for(let z=-28;z<=28;z+=4.8)g.world.covers.push({x,z,w:2.8,d:2.8,hp:Infinity,kind:'jungle-tree'});b.visual.root.position.set(-12,2.5,-12);g.player.visual.root.position.set(2.4,0,2.4);for(let i=0;i<1400;i++){g.elapsed+=.05;g.bosses.update(g,b,.05);if(g.bosses.states.get(b).phase==='exposed')return b.visual.root.position.y<.2;}return false;});expect(rested).toBe(true);
});
test('Easy changes actual hull while harder modes preserve health and scale finite waves',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const rows=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};const rows=[];for(const difficulty of ['easy','normal','hard','crazy']){g.save.difficulty=difficulty;g.start(3,0);const hull=g.player.hp,initial=g.enemies.length;for(const u of g.enemies)u.dead=true;g.elapsed=12;g.step(.02);rows.push({difficulty,hull,initial,wave:g.enemies.filter((u:any)=>!u.dead).length});}return rows;});expect(rows.map(r=>r.hull)).toEqual([360,240,240,240]);expect(rows.map(r=>r.wave)).toEqual([0,0,0,0]);expect(rows.map(r=>r.initial)).toEqual([24,24,48,96]);
});
test('Crazy city retains all actors and a readable mobile HUD in Low detail',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await page.goto('http://127.0.0.1:5178/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const result=await page.evaluate(async()=>{const g=(window as any).__steel;g.frame=()=>{};g.save.difficulty='crazy';g.start(13,2);g.player.visual.root.position.set(0,0,-8);g.world.target.copy(g.player.visual.root.position);g.world.update(0,g.player.visual.root.position);g.updateHud();const high={calls:g.world.renderer.info.render.calls,triangles:g.world.renderer.info.render.triangles};g.pause();await g.world.load(true);g.world.settings(true);g.resume();g.world.update(0,g.player.visual.root.position);g.updateHud();return {high,low:{calls:g.world.renderer.info.render.calls,triangles:g.world.renderer.info.render.triangles},enemies:g.enemies.length,bosses:g.enemies.filter((u:any)=>u.role==='boss').length,width:document.documentElement.scrollWidth,radio:document.querySelector('#radio')!.getBoundingClientRect().top,hud:document.querySelector('.mission-hud')!.getBoundingClientRect().bottom};});expect(result.enemies).toBe(148);expect(result.bosses).toBe(4);expect(result.low.triangles).toBeLessThan(result.high.triangles*.5);expect(result.width).toBeLessThanOrEqual(390);expect(result.radio).toBeGreaterThan(result.hud);console.log('CRAZY_MOBILE_RENDER',JSON.stringify(result));await expect(page.locator('.move-pad')).toBeVisible();await expect(page.locator('.aim-pad')).toBeVisible();await page.screenshot({path:'test-results/crazy-city-low.png'});await context.close();
});
