import {test,expect} from '@playwright/test';
test('enemy tanks trigger mines and the same mine cannot detonate twice',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.player.visual.root.position.set(65,0,55);for(const u of g.enemies)u.dead=true;const mine=g.world.activities.find((a:any)=>a.kind==='mine');const tank=g.makeUnit(mine.x,mine.z,'raider'),soldier=g.makeUnit(mine.x+1,mine.z,'rifleman');tank.visual.root.position.set(mine.x,0,mine.z);soldier.visual.root.position.set(mine.x+1,0,mine.z);tank.hp=35;g.enemies=[tank,soldier];g.updateActivities(.01);const once=g.kills;g.updateActivities(.01);return {spent:mine.spent,hidden:!mine.mesh.visible,tankDead:tank.dead,soldierDead:soldier.dead,once:g.kills===once};});expect(r).toEqual({spent:true,hidden:true,tankDead:true,soldierDead:true,once:true});
});
test('gasoline crates damage tanks, soldiers and cover with bounded chain reactions',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;for(const u of g.enemies)u.dead=true;g.player.visual.root.position.set(65,0,55);const fuel=g.world.covers.find((c:any)=>c.kind==='fuelcrate'),barrel=g.world.covers.find((c:any)=>c.kind==='barrel');barrel.x=fuel.x+3;barrel.z=fuel.z;barrel.mesh.position.set(barrel.x,0,barrel.z);const crate=g.world.covers.find((c:any)=>c.kind==='crate');crate.x=fuel.x;crate.z=fuel.z+2;crate.mesh.position.set(crate.x,0,crate.z);const tank=g.makeUnit(fuel.x+2,fuel.z,'heavy'),soldier=g.makeUnit(fuel.x,fuel.z+1,'rifleman'),far=g.makeUnit(fuel.x,fuel.z+15,'heavy');tank.visual.root.position.set(fuel.x+2,0,fuel.z);soldier.visual.root.position.set(fuel.x,0,fuel.z+1);far.visual.root.position.set(fuel.x,0,fuel.z+15);g.enemies=[tank,soldier,far];const hp=tank.hp,outside=far.hp;g.hitCover(fuel,999);const after=tank.hp;g.hitCover(fuel,999);return {fuel:!fuel.mesh.visible,chain:barrel.hp<=0,cover:crate.hp<=0,tank:tank.hp<hp,soldier:soldier.dead,outside:far.hp===outside,once:tank.hp===after};});for(const [key,value] of Object.entries(r))expect(value,key).toBe(true);
});
test('Blender rockets have rear exhaust, smoke and shared resource cleanup',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.weapon=2;g.player.visual.root.position.set(0,0,35);g.player.aim=Math.PI;g.shoot(g.player,true);const shot=g.shots.at(-1);let fins=false;shot.mesh.traverse((o:any)=>{if(o.isMesh&&o.material.name==='RocketMetal'){o.geometry.computeBoundingBox();if(o.geometry.boundingBox.max.x-o.geometry.boundingBox.min.x>1)fins=true;}});g.trailClock=0;g.updateShots(.05);shot.mesh.updateMatrixWorld(true);const tail=shot.mesh.position.clone();shot.mesh.getObjectByName('Exhaust').getWorldPosition(tail);const smoke=g.world.fx.particles.filter((p:any)=>p.kind==='smoke').at(-1),behind=tail.z>shot.mesh.position.z;const nozzleSmoke=smoke.mesh.position.distanceTo(tail)<.001;g.specialAmmo[1]=1;g.weapon=4;g.aimPoint.set(0,0,0);g.shoot(g.player,true);const shared=g.special.arcs[0].mesh.userData.shared;g.special.update(g,.5);const arcNozzle=!!g.special.arcs[0].mesh.getObjectByName('Exhaust');g.start(0);return {fins,behind,nozzleSmoke,shared,arcNozzle,clean:g.special.arcs.length===0&&g.shots.length===0};});expect(r).toEqual({fins:true,behind:true,nozzleSmoke:true,shared:true,arcNozzle:true,clean:true});
});
