import {test,expect} from '@playwright/test';
test('mobile fullscreen enters and exits without resetting the mission',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true});const page=await context.newPage();await page.goto('/?e2e');const button=page.locator('.mobile-fullscreen button');await button.click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await expect(button).toHaveAttribute('aria-pressed','true');await page.locator('[data-action=deploy]').click();await page.locator('#pause').click();await page.locator('[data-action=fullscreen]').click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(false);await expect(page.locator('body')).toHaveAttribute('data-phase','paused');await page.getByRole('button',{name:'RESUME OPERATION'}).click();await expect(page.locator('body')).toHaveAttribute('data-phase','playing');await context.close();
});
test('unsupported fullscreen explains the mobile fallback and leaves Deploy usable',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();await page.addInitScript(()=>Object.defineProperty(document,'fullscreenEnabled',{get:()=>false}));await page.goto('/?e2e');await page.locator('.mobile-fullscreen button').click();await expect(page.locator('.fullscreen-notice')).toContainText('Rotate your phone');await expect(page.locator('.mobile-fullscreen button')).toHaveAttribute('aria-pressed','false');await page.locator('[data-action=deploy]').click();await expect(page.locator('body')).toHaveAttribute('data-phase','playing');await context.close();
});
test('rejected fullscreen requests recover the button without an uncaught error',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Element.prototype.requestFullscreen=()=>Promise.reject(new Error('Denied'));Object.defineProperty(document,'fullscreenEnabled',{get:()=>true});});await page.goto('/?e2e');await page.locator('.menu-settings>summary').click();const button=page.locator('.menu-settings [data-action=fullscreen]');await button.click();await expect(page.locator('.fullscreen-notice')).toContainText('could not enter fullscreen');await expect(button).toBeEnabled();expect(errors).toEqual([]);
});
