import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';

async function battle(page:Page){
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.world.covers=[];g.world.activities=[];g.world.navigationRevision++;g.enemies=[];g.lootRandom=()=>.99;g.player.visual.root.position.set(0,0,0);});
}

test('guided support rejects empty, paused, dead and duplicate calls without spending extra cooldown',async({page})=>{
 await battle(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;const empty=!g.callArtillery()&&g.artilleryCooldown===0;const u=g.makeUnit(20,0,'heavy');u.visual.root.position.set(20,0,0);g.enemies=[u];g.pause();const paused=!g.callArtillery()&&g.artilleryCooldown===0;g.resume();g.player.dead=true;const dead=!g.callArtillery()&&g.artilleryCooldown===0;g.player.dead=false;const accepted=g.callArtillery();const count=g.strikes.length;g.callArtillery();return {empty,paused,dead,accepted,count,duplicate:g.strikes.length===count&&g.artilleryCooldown===28};});expect(r).toEqual({empty:true,paused:true,dead:true,accepted:true,count:2,duplicate:true});
});

test('salvos spread across distinct enemies first, reinforce armor, and exclude distant or dead targets',async({page})=>{
 await battle(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;for(let i=0;i<16;i++){const a=i*Math.PI/8,u=g.makeUnit(Math.sin(a)*28,Math.cos(a)*28,i%2?'rifleman':'heavy');u.visual.root.position.set(Math.sin(a)*28,0,Math.cos(a)*28);g.enemies.push(u);}const far=g.makeUnit(67,50,'heavy');far.visual.root.position.set(67,0,50);g.enemies.push(far);const dead=g.makeUnit(10,0,'heavy');dead.visual.root.position.set(10,0,0);dead.dead=true;g.enemies.push(dead);g.callArtillery();const full=g.strikes.length===12&&new Set(g.strikes.map((s:any)=>s.target)).size===12&&!g.strikes.some((s:any)=>s.target===far||s.target===dead);g.clearBarrage();g.artilleryCooldown=0;g.enemies=g.enemies.slice(0,3);g.callArtillery();return {full,count:g.strikes.length,locks:[...g.guided.locks.values()].sort(),bounded:g.strikes.every((s:any)=>Math.abs(s.from.x)<=72&&Math.abs(s.from.z)<=60)};});expect(r).toEqual({full:true,count:5,locks:[1,2,2],bounded:true});
});

test('missiles track moving targets over cover, pause, retarget destroyed enemies and clean up on retry',async({page})=>{
 await battle(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;const u=g.makeUnit(20,0,'heavy');u.visual.root.position.set(20,0,0);u.hp=u.max=10000;g.enemies=[u];g.world.covers=[{x:10,z:0,w:4,d:12,hp:Infinity,kind:'hill'}];g.callArtillery();g.updateActivities(.5);const warned=g.strikes.every((s:any)=>!s.bomb.visible)&&u.hp===10000;g.updateActivities(.8);u.visual.root.position.set(26,0,8);g.updateActivities(.05);const following=g.strikes.every((s:any)=>s.point.x===26&&s.marker.position.z===8)&&g.strikes.some((s:any)=>s.bomb.visible&&s.bomb.position.y>3);const age=g.strikes[0].age;g.pause();g.step(2);g.guided.update(g,2);const paused=g.strikes[0].age===age;g.resume();g.world.covers=[];const next=g.makeUnit(-25,0,'heavy');next.visual.root.position.set(-25,0,0);g.enemies.push(next);u.dead=true;g.updateActivities(.01);const retarget=g.strikes.every((s:any)=>s.target===next);const meshes=g.strikes.flatMap((s:any)=>[s.marker,s.bomb]);g.start(0);return {warned,following,paused,retarget,clean:g.strikes.length===0&&g.guided.locks.size===0&&meshes.every((m:any)=>!m.parent)};});expect(Object.values(r).every(Boolean),JSON.stringify(r)).toBe(true);
});

test('guided warheads damage tanks, airborne bosses and nearby scenery while sparing allies from direct blasts',async({page})=>{
 await battle(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;g.start(2,0);g.enemies=[];g.world.covers=[];g.world.activities=[];g.world.navigationRevision++;g.player.visual.root.position.set(0,0,0);g.convoy.position.set(0,0,2);const u=g.makeUnit(1,1,'heavy');u.visual.root.position.set(1,0,1);u.hp=u.max=1000;g.enemies=[u];const mesh=g.world.clone('house');mesh.position.set(4,0,1);g.world.covers=[{kind:'house',mesh,x:4,z:1,w:4,d:4,hp:1000}];const hp=g.player.hp;g.callArtillery();g.updateActivities(1.99);const warning=u.hp===1000;g.updateActivities(2);const after=u.hp;g.updateActivities(5);const direct={warning,tank:after<800,house:g.world.covers[0].hp<1000,allies:g.player.hp===hp&&g.convoyHealth===1040,once:u.hp===after&&g.strikes.length===0};g.world.covers=[];g.enemies=[];g.artilleryCooldown=0;const heli=g.makeUnit(20,0,'boss','helicopter');heli.visual.root.position.set(20,7,0);heli.hp=1000;g.enemies=[heli];g.callArtillery();g.updateActivities(4);return {...direct,air:heli.hp<1000};});expect(Object.values(r).every(Boolean),JSON.stringify(r)).toBe(true);
});

test('support fuel chain reactions remain dangerous but the shared shield protects the convoy',async({page})=>{
 await battle(page);const rows=await page.evaluate(()=>{const g=(window as any).__steel;const rows=[];for(const shield of [false,true]){g.start(2,0);g.world.covers=[];g.world.activities=[];g.enemies=[];g.world.navigationRevision++;g.player.visual.root.position.set(0,0,0);g.convoy.position.set(0,0,2);const u=g.makeUnit(4,0,'heavy');u.visual.root.position.set(4,0,0);u.hp=1000;g.enemies=[u];const mesh=g.world.clone('fuelcrate');mesh.position.set(2,0,1);const fuel={kind:'fuelcrate',mesh,x:2,z:1,w:2,d:2,hp:25};g.world.covers=[fuel];g.shieldTime=shield?10:0;const hp=g.player.hp;g.callArtillery();g.updateActivities(5);rows.push({shield,fuel:fuel.hp<=0,player:g.player.hp===hp,convoy:g.convoyHealth===1040});}return rows;});expect(rows).toEqual([{shield:false,fuel:true,player:false,convoy:false},{shield:true,fuel:true,player:true,convoy:true}]);
});

test('guidance damage is stable at 30/60 FPS and either quality, and fleeing targets leave a bounded last-known strike',async({page})=>{
 await battle(page);const rows=await page.evaluate(()=>{const g=(window as any).__steel,rows=[];for(const low of [false,true])for(const fps of [30,60]){g.clearBarrage();g.artilleryCooldown=0;g.enemies=[];g.world.settings(low);const u=g.makeUnit(20,0,'heavy');u.visual.root.position.set(20,0,0);u.hp=u.max=1000;g.enemies=[u];g.callArtillery();for(let i=0;i<fps*5;i++)g.updateActivities(1/fps);rows.push({hp:u.hp,clean:g.strikes.length===0});}return rows;});expect(rows.every(r=>r.clean)).toBe(true);for(const row of rows)expect(row.hp).toBeCloseTo(rows[0].hp);
 const bounded=await page.evaluate(()=>{const g=(window as any).__steel;g.artilleryCooldown=0;g.enemies[0].visual.root.position.set(20,0,0);g.callArtillery();g.enemies[0].visual.root.position.set(90,0,0);g.updateActivities(.1);return g.strikes.every((s:any)=>s.target===null&&s.point.x===20);});expect(bounded).toBe(true);
});

for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:844,height:390}])test(`guided missile and convoy shield controls and graphics ${viewport.width}`,async({browser})=>{
 const mobile=viewport.width!==1440,c=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile}),page=await c.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await battle(page);
 await page.evaluate(()=>{const g=(window as any).__steel;g.start(2,0);g.frame=()=>{};for(const e of g.enemies)e.visual.root.visible=false;for(const c of g.world.covers)c.mesh.visible=false;g.enemies=[];g.world.covers=[];g.world.activities=[];g.world.navigationRevision++;g.player.visual.root.position.set(-4,0,10);g.convoy.position.set(4,0,10);for(let i=0;i<6;i++){const u=g.makeUnit(-20+i*8,-14,'heavy');u.visual.root.position.set(-20+i*8,0,-14);u.hp=u.max=1000;g.enemies.push(u);}g.world.camera.position.set(8,55,42);g.world.camera.lookAt(0,3,0);g.world.camera.updateMatrixWorld();});
 if(mobile){await page.locator('#shield').tap();await page.locator('#artillery').tap();}else{await page.keyboard.press('q');await page.keyboard.press('r');}await expect(page.locator('#artillery-label')).toContainText('STRIKE');await expect(page.locator('#artillery')).toBeDisabled();
 for(const low of [false,true]){const r=await page.evaluate(async low=>{const g=(window as any).__steel;if(low){g.clearBarrage();g.artilleryCooldown=0;g.pause();await g.changeQuality();g.resume();g.callArtillery();}g.updatePlayer(.01);g.updateActivities(1.8);g.world.camera.position.set(8,55,42);g.world.camera.lookAt(0,3,0);g.world.camera.updateMatrixWorld();g.world.renderer.render(g.world.scene,g.world.camera);g.updateHud();return {count:g.strikes.length,visible:g.strikes.filter((s:any)=>s.bomb.visible).length,shield:g.convoy.getObjectByName('ConvoyShield').visible,overflow:document.documentElement.scrollWidth>innerWidth,error:g.world.renderer.getContext().getError()};},low);expect(r.count).toBe(12);expect(r.visible).toBeGreaterThan(0);expect(r.shield).toBe(true);expect(r.overflow).toBe(false);expect(r.error).toBe(0);await expect(page.locator('#objective')).toContainText('100% · SHIELDED');await page.screenshot({path:`test-results/guided-support-${viewport.width}-${low?'low':'detailed'}.png`});}
 expect(errors).toEqual([]);await c.close();
});


test('a guided kill ends the battle once and cancels spare missiles during the results delay',async({page})=>{
 await battle(page);const r=await page.evaluate(()=>{const g=(window as any).__steel;const u=g.makeUnit(20,0,'raider');u.visual.root.position.set(20,0,0);u.cooldown=1e6;g.enemies=[u];g.callArtillery();const meshes=g.strikes.flatMap((s:any)=>[s.marker,s.bomb]);for(let i=0;i<240&&g.phase==='playing';i++)g.step(1/60);const credit=g.save.credits,finishing=g.phase==='finishing',clean=g.strikes.length===0&&meshes.every((m:any)=>!m.parent);g.step(.79);const delay=g.phase==='finishing';g.step(.02);g.complete();return {finishing,clean,delay,once:g.save.credits===credit&&g.phase==='depot'};});expect(Object.values(r).every(Boolean),JSON.stringify(r)).toBe(true);
});
