import {addTestPickups} from './activity-fixtures';
import {test,expect} from '@playwright/test';
test('infantry are active combatants and do not count as tank objectives',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;const infantry=g.enemies.filter((u:any)=>g.isInfantry(u));const count=infantry.length,roles=[...new Set(infantry.map((u:any)=>u.role))];const soldier=infantry[0];g.world.covers=[];g.world.navigationRevision++;g.player.visual.root.position.set(0,0,22);soldier.visual.root.position.set(0,0,0);soldier.cooldown=.01;const z=soldier.visual.root.position.z;g.updateEnemies(.1);const attacked=g.shots.some((s:any)=>!s.friendly&&s.damage===3),moved=soldier.visual.root.position.z!==z;const kills=g.kills,wrecks=g.world.wrecks.length;for(const u of infantry)g.damageUnit(u,9999,g.player.visual.root.position);return {count,roles,attacked,moved,objectiveUnchanged:g.kills===kills,wrecksUnchanged:g.world.wrecks.length===wrecks,dead:infantry.every((u:any)=>u.dead&&!u.visual.root.visible)};});expect(r.count).toBe(13);expect(r.roles).toEqual(['rifleman','rocketeer']);expect(r.attacked).toBe(true);expect(r.moved).toBe(true);expect(r.objectiveUnchanged&&r.wrecksUnchanged&&r.dead).toBe(true);
});
test('collectible laser obeys cover and arc rocket flies over it with finite ammo',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();await addTestPickups(page,['laser','arc']);const r=await page.evaluate(()=>{const g=(window as any).__steel;for(const u of g.enemies)u.dead=true;const laser=g.world.activities.find((a:any)=>a.kind==='laser'),arc=g.world.activities.find((a:any)=>a.kind==='arc');g.player.visual.root.position.set(laser.x,0,laser.z);g.updateActivities(.01);const laserFound=g.weapon===3&&g.specialAmmo[0]===12&&laser.spent;g.player.visual.root.position.set(arc.x,0,arc.z);g.updateActivities(.01);const arcFound=g.weapon===4&&g.specialAmmo[1]===6&&arc.spent;
 const wall=g.world.covers.find((c:any)=>c.kind==='steelwall'),enemy=g.makeUnit(wall.x,wall.z-6,'heavy');enemy.visual.root.position.set(wall.x,0,wall.z-6);enemy.hp=10000;g.enemies=[enemy];g.world.covers=[wall];g.world.navigationRevision++;g.player.visual.root.position.set(wall.x,0,wall.z+6);g.player.aim=Math.PI;g.aimPoint.copy(enemy.visual.root.position);g.weapon=3;g.shoot(g.player,true);const blocked=enemy.hp===10000&&g.specialAmmo[0]===11;
 g.weapon=4;g.shoot(g.player,true);g.special.update(g,.75);const airborne=g.special.arcs[0].mesh.position.y>15&&enemy.hp===10000;g.special.update(g,.76);const landed=enemy.hp<10000&&g.special.arcs.length===0&&g.specialAmmo[1]===5;
 wall.hp=0;enemy.hp=10000;g.weapon=3;g.specialAmmo[0]=1;g.shoot(g.player,true);const laserHit=enemy.hp<10000&&g.specialAmmo[0]===0&&g.weapon===0;g.start(0);return {laserFound,arcFound,blocked,airborne,landed,laserHit,reset:g.special.beams.length===0&&g.special.arcs.length===0&&g.specialAmmo.every((a:number)=>a===0)};});for(const [key,value] of Object.entries(r))expect(value,key).toBe(true);
});
test('mobile special weapon discovery and five-choice armory',async({browser})=>{
 const c=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const p=await c.newPage();await p.goto('/?e2e');await p.getByRole('button',{name:'DEPLOY'}).tap();await addTestPickups(p,['laser']);await p.locator('#weapon').tap();await expect(p.locator('[data-weapon="4"]')).toContainText('Shop / map cache');await expect(p.locator('[data-weapon="5"]')).toBeDisabled();await p.locator('#weapon').tap();await p.evaluate(()=>{const g=(window as any).__steel;const laser=g.world.activities.find((a:any)=>a.kind==='laser');g.player.visual.root.position.set(laser.x,0,laser.z);g.updateActivities(.01);});await p.locator('#weapon').tap();await p.locator('[data-weapon="4"]').tap();await expect(p.locator('#weapon-label')).toContainText('Pulse laser');await p.locator('#weapon').tap();await p.screenshot({path:'test-results/infantry-special-mobile.png'});await c.close();
});
