import {test,expect} from '@playwright/test';
import {awardStage} from '../src/three/results';
import {freshSave} from '../src/three/campaign';
test('health star thresholds reward survival without changing earned credits',()=>{for(const [hp,stars] of [[1,1],[39,1],[40,2],[74,2],[75,3],[100,3]])expect(awardStage(freshSave(),0,45,hp,100,0).stars).toBe(stars);});
for(const viewport of [{width:320,height:568},{width:1440,height:900},{width:390,height:844},{width:844,height:390}])test(`clear menu and categorized shop ${viewport.width}`,async({browser})=>{
 const context=await browser.newContext({viewport,hasTouch:viewport.width<1000,isMobile:viewport.width<1000});const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?e2e');await expect(page.locator('[data-action=deploy]')).toBeVisible();await expect(page.locator('[data-action=difficulty]').first()).toBeHidden();await expect(page.locator('[data-action=quality]')).toBeHidden();await page.screenshot({path:`test-results/menu-${viewport.width}.png`,fullPage:true});
 await page.locator('.mission-setup>summary').click();await page.locator('[data-action=difficulty][data-value=hard]').click();await expect(page.locator('.mission-setup')).toHaveAttribute('open','');await expect(page.locator('[data-action=difficulty][data-value=hard]')).toHaveAttribute('aria-pressed','true');
 await page.locator('.menu-settings>summary').click();await page.locator('[data-action=sound]').click();await expect(page.locator('.menu-settings')).toHaveAttribute('open','');
 await page.locator('[data-action=shop]').click();await expect(page.locator('[data-weapon-card="0"]')).toBeVisible();await expect(page.locator('[data-action=buy]').first()).toBeHidden();await page.locator('[data-action=shop-tab][data-value=systems]').click();await expect(page.locator('[data-action=buy]').first()).toBeVisible();await expect(page.locator('[data-weapon-card="0"]')).toBeHidden();await page.screenshot({path:`test-results/shop-${viewport.width}.png`,fullPage:true});await page.locator('[data-action=shop-tab][data-value=support]').click();await expect(page.locator('[data-action=buy-auto]')).toBeVisible();await page.locator('[data-action=shop-tab][data-value=skins]').click();await expect(page.locator('.skin-card').first()).toBeVisible();await page.locator('[data-action=shop-back]').click();await page.locator('[data-action=deploy]').click();await expect(page.locator('body')).toHaveAttribute('data-phase','playing');await page.evaluate(()=>{const g=(window as any).__steel;g.player.hp=g.player.max*.5;g.complete();});await expect(page.getByRole('img',{name:'2 out of 3 stars'})).toBeVisible();await page.screenshot({path:`test-results/stars-${viewport.width}.png`,fullPage:true});expect(await page.locator('#overlay').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);expect(errors).toEqual([]);await context.close();
});
