import {test,expect} from '@playwright/test';
import {encounterSize} from '../src/three/campaign';
import {DIFFICULTIES,mode} from '../src/three/difficulty';
import {salvageReward} from '../src/three/loot';

test('rifles dominate the expanded roster and loot contents shrink with challenge',()=>{
 expect(encounterSize(0,0,'normal')).toMatchObject({armor:5,riflemen:9,rocketeers:4,jeeps:1,bosses:0});
 for(let stage=0;stage<16;stage++)for(let level=0;level<3;level++)for(const difficulty of DIFFICULTIES){const normal=encounterSize(stage,level,'normal'),roster=encounterSize(stage,level,difficulty);for(const key of ['armor','riflemen','rocketeers','jeeps'] as const)expect(roster[key]).toBe(normal[key]*mode(difficulty).enemies);expect(roster.riflemen).toBeGreaterThanOrEqual(roster.rocketeers*2);expect(roster.bosses).toBe(level===2?mode(difficulty).bosses:0);}
 for(const roll of [.1,.4,.6,.9])for(const difficulty of DIFFICULTIES){const early=salvageReward(roll,difficulty,0),late=salvageReward(roll,difficulty,2);expect(late.kind).toBe(early.kind);expect(late.amount).toBeLessThanOrEqual(early.amount);expect(late.amount).toBeLessThanOrEqual(salvageReward(roll,'easy',2).amount);}
});

test('distant tanks patrol toward the road, keep a wider leash and return after a lost pursuit',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();
 const r=await page.evaluate(async()=>{const g=(window as any).__steel;g.frame=()=>{};const {assignPatrol}=await import('/src/three/patrols.ts');g.enemies=[];g.world.covers=[];g.world.navigationRevision++;g.world.layout.points=[{x:0,z:-50},{x:0,z:50}];g.world.layout.length=100;g.player.visual.root.position.set(-65,0,55);
 const create=(x:number,z:number,role:string,index:number)=>{const e=g.makeUnit(x,z,role);e.encounter={group:index,anchor:{x:0,z},meters:z+50,active:false};g.enemies.push(e);assignPatrol(g,e,index);return e;};
 const far=create(22,0,'raider',1),near=create(4,-30,'raider',3),guard=create(4,35,'raider',0);const remote=create(50,30,'heavy',5),remoteApproach=Math.min(...remote.patrol.points.map((p:any)=>Math.abs(p.x)));const before=guard.visual.root.position.clone();let approach=22,maxRadius=0;
 for(let n=0;n<700;n++){g.elapsed+=.05;g.updateEnemies(.05);approach=Math.min(approach,Math.abs(far.visual.root.position.x));maxRadius=Math.max(maxRadius,Math.hypot(far.visual.root.position.x-22,far.visual.root.position.z));}
 const quiet=g.shots.length===0&&!far.encounter.active,held=guard.visual.root.position.equals(before)&&!guard.patrol;
 far.visual.root.position.set(50,0,30);far.encounter.active=true;far.searchUntil=0;g.enemies=[far];const home=far.patrol.home,dist=()=>Math.hypot(far.visual.root.position.x-home.x,far.visual.root.position.z-home.z),initial=dist();for(let n=0;n<300;n++){g.elapsed+=.05;g.updateEnemies(.05);}const returned=dist()<initial-12&&!far.encounter.active;
 g.player.visual.root.position.set(far.visual.root.position.x-15,0,far.visual.root.position.z);far.cooldown=0;g.updateEnemies(.2);
 return {remoteApproach,far:far.patrol.radius,near:near.patrol.radius,approach,maxRadius,quiet,held,returned,detected:far.encounter.active&&g.shots.length>0};
 });expect(r.remoteApproach).toBeLessThan(32);expect(r.far).toBeGreaterThan(r.near);expect(r.approach).toBeLessThan(5);expect(r.maxRadius).toBeLessThanOrEqual(r.far+2.01);expect(r.quiet&&r.held&&r.returned&&r.detected,JSON.stringify(r)).toBe(true);
});

test('patrol navigation goes around cover with a bounded path refresh rate',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(async()=>{const g=(window as any).__steel;g.frame=()=>{};const {assignPatrol}=await import('/src/three/patrols.ts');const {circleBox}=await import('/src/three/rules.ts');g.enemies=[];g.world.covers=[];g.world.navigationRevision++;g.world.layout.points=[{x:0,z:-50},{x:0,z:50}];g.world.layout.length=100;g.player.visual.root.position.set(-65,0,55);const e=g.makeUnit(22,0,'raider');e.encounter={group:0,anchor:{x:0,z:0},meters:50,active:false};g.enemies=[e];g.world.covers=[{x:12,z:0,w:2,d:18,hp:Infinity,kind:'hill'}];g.world.navigationRevision++;assignPatrol(g,e,1);let calls=0,clipped=false,minX=22;const next=g.navigation.next.bind(g.navigation);g.navigation.next=(...args:any[])=>{calls++;return next(...args);};for(let n=0;n<800;n++){g.elapsed+=.05;g.updateEnemies(.05);minX=Math.min(minX,e.visual.root.position.x);clipped ||=circleBox(e.visual.root.position,g.unitRadius(e),g.world.covers[0]);}return {calls,clipped,minX};});expect(r.clipped).toBe(false);expect(r.minX).toBeLessThan(8);expect(r.calls).toBeGreaterThan(0);expect(r.calls).toBeLessThan(90);
});

test('jeep fires weak three-round bursts, takes damage and cannot create loot',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.enemies=[];g.world.covers=[];g.world.navigationRevision++;g.player.visual.root.position.set(0,0,20);const jeep=g.makeUnit(0,0,'jeep');g.enemies=[jeep];jeep.cooldown=0;for(let i=0;i<9;i++){g.elapsed+=.05;g.updateEnemies(.05);}const burst=g.shots.map((s:any)=>s.damage);for(let i=0;i<10;i++){g.elapsed+=.05;g.updateEnemies(.05);}const pause=g.shots.length===3,hp=g.player.hp;for(let i=0;i<70;i++)g.updateShots(1/60);const damage=hp-g.player.hp;let rolls=0;g.lootRandom=()=>{rolls++;return .1;};g.damageUnit(jeep,1000,g.player.visual.root.position);const infantry=g.makeUnit(-10,0,'rifleman');g.enemies.push(infantry);g.damageUnit(infantry,1000,g.player.visual.root.position);return {burst,pause,damage,dead:jeep.dead,rolls,goal:g.kills===1,wreck:g.world.wrecks.length===1};});expect(r.burst).toEqual([3,3,3]);expect(r.pause&&r.dead&&r.goal&&r.wreck).toBe(true);expect(r.rolls).toBe(0);expect(r.damage).toBeGreaterThan(0);expect(r.damage).toBeLessThanOrEqual(12);
});

test('wreck loot uses one-third odds, stays local and respects ammo caps',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(async()=>{const g=(window as any).__steel;g.frame=()=>{};g.enemies=[];g.world.covers=[];g.world.activities=[];g.world.navigationRevision++;g.player.visual.root.position.set(0,0,40);const rolls=[.34,1/3,.99,.1,.6];let consumed=0;g.lootRandom=()=>{consumed++;return rolls.shift()??.99;};for(let i=0;i<4;i++){const tank=g.makeUnit(i*8,0,'raider');g.enemies.push(tank);g.damageUnit(tank,1000,g.player.visual.root.position);g.damageUnit(tank,1000,g.player.visual.root.position);}const crate=g.world.activities[0],local=Math.hypot(crate.x-24,crate.z)<=8.01;g.specialAmmo[0]=12;g.player.visual.root.position.set(crate.x,0,crate.z);g.updateActivities(.01);const preserved=!crate.spent;g.specialAmmo[0]=11;g.updateActivities(.01);const capped=crate.spent&&g.specialAmmo[0]===12;g.updateActivities(.01);const once=g.specialAmmo[0]===12;return {consumed,count:g.world.activities.length,kind:crate.kind,amount:crate.amount,local,preserved,capped,once};});expect(r).toEqual({consumed:5,count:1,kind:'laser',amount:6,local:true,preserved:true,capped:true,once:true});
});

for(const mobile of [false,true])test(`crewed jeep retains its moving rig in Detailed and Low on ${mobile?'mobile':'desktop'}`,async({browser})=>{
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:800},hasTouch:mobile,isMobile:mobile}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();
 const high=await page.evaluate(mobile=>{const g=(window as any).__steel;g.frame=()=>{};const jeep=g.enemies.find((e:any)=>e.role==='jeep');g.world.arena.visible=false;g.player.visual.root.visible=false;for(const e of g.enemies)e.visual.root.visible=e===jeep;g.world.scene.fog=null;const p=jeep.visual.root.position;g.world.camera.position.set(p.x+(mobile?9:6),mobile?6:5,p.z+(mobile?10:7));g.world.camera.lookAt(p.x,1,p.z);g.elapsed=1;jeep.visual.root.userData.walking=true;g.syncVisual(jeep);g.world.renderer.render(g.world.scene,g.world.camera);return {triangles:g.world.renderer.info.render.triangles,rig:['WheelFL','WheelFR','WheelRL','WheelRR','Muzzle'].every(name=>!!jeep.visual.root.getObjectByName(name))};},mobile);await page.screenshot({path:`test-results/jeep-${mobile?'mobile':'desktop'}-detailed.png`});
 const low=await page.evaluate(async()=>{const g=(window as any).__steel,jeep=g.enemies.find((e:any)=>e.role==='jeep'),p=jeep.visual.root.position.clone();await g.world.load(true);g.world.settings(true);g.syncVisual(jeep);g.world.renderer.render(g.world.scene,g.world.camera);return {triangles:g.world.renderer.info.render.triangles,stable:jeep.visual.root.position.equals(p),rig:['WheelFL','WheelFR','WheelRL','WheelRR'].every(name=>Math.abs(jeep.visual.root.getObjectByName(name)?.rotation.x)>1),overflow:document.documentElement.scrollWidth>innerWidth};});await page.screenshot({path:`test-results/jeep-${mobile?'mobile':'desktop'}-low.png`});expect(high.rig&&low.rig&&low.stable&&!low.overflow,JSON.stringify({high,low})).toBe(true);expect(low.triangles).toBeLessThan(high.triangles*.6);expect(errors).toEqual([]);await context.close();
});


test('crew batching preserves authored finishes and animated pivots at both detail tiers',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const rows=await page.evaluate(async()=>{const g=(window as any).__steel;g.frame=()=>{};const rows=[];for(const low of [false,true]){await g.world.load(low);for(const name of ['rifleman','rocketeer','scout-jeep']){const root=g.world.templates.get(name);let meshes=0,metal=false,matte=false,colors=new Set<string>();root.traverse((o:any)=>{if(!o.isMesh)return;meshes++;const c=o.geometry.attributes.color,f=o.geometry.attributes.crewSurface;if(!c||!f)throw new Error('Missing crew finish attributes');for(let i=0;i<c.count;i++){colors.add([c.getX(i),c.getY(i),c.getZ(i)].map(v=>v.toFixed(2)).join(','));metal ||=f.getY(i)>.5;matte ||=f.getX(i)>.7;}if(o.material.name!=='CrewSurface'||o.material.customProgramCacheKey()!=='crew-surface-v1')throw new Error('Crew shader lost');});rows.push({low,name,meshes,metal,matte,colors:colors.size});}}return rows;});for(const r of rows){expect(r.meshes).toBeLessThanOrEqual(r.name==='scout-jeep'?6:3);expect(r.metal&&r.matte).toBe(true);expect(r.colors).toBeGreaterThanOrEqual(5);}
});
