import {test,expect} from '@playwright/test';

for(const kind of ['quad-mech','siege-mech','missile-truck'])test(`${kind} has its own warned attack, exposed core and death cleanup`,async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(kind=>{const g=(window as any).__steel;g.frame=()=>{};g.world.covers=[];g.enemies=[];const b=g.makeUnit(0,0,'boss',kind);g.enemies=[b];b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,30);g.player.hp=10000;const fired:any[]=[];const round=g.bossRound.bind(g);g.bossRound=(u:any,aim:number,damage:number,muzzle:string,...rest:any[])=>{if(muzzle?.startsWith('GunMuzzle'))fired.push({damage,muzzle});round(u,aim,damage,muzzle,...rest);};g.bosses.update(g,b,4.1);const s=g.bosses.states.get(b),warned=s.phase==='charging',zones=s.markers.map((m:any)=>m.geometry.parameters.outerRadius),targets=JSON.stringify(s.targets),hp=g.player.hp;
  g.player.visual.root.position.x=32;g.bosses.update(g,b,s.time-.01);const safe=g.player.hp===hp,locked=JSON.stringify(s.targets)===targets,launched=kind==='quad-mech'||s.rockets.every((r:any)=>r.visible&&r.userData.rocket);g.bosses.update(g,b,.02);for(let i=0;i<70;i++){g.bosses.update(g,b,1/60);g.updateShots(1/60);g.special.update(g,1/60);}
  const exposed=g.bosses.multiplier(b)>1&&b.visual.root.getObjectByName('Core').visible;g.damageUnit(b,999999,g.player.visual.root.position,true);const clean=!g.bosses.states.has(b)&&s.markers.length===0&&s.rockets.length===0;return {warned,zones,safe,locked,launched,exposed,clean,fired};
 },kind);expect(r.warned&&r.safe&&r.locked&&r.launched&&r.exposed&&r.clean,JSON.stringify(r)).toBe(true);if(kind==='quad-mech'){expect(r.fired).toHaveLength(8);expect(new Set(r.fired.map((s:any)=>s.muzzle)).size).toBe(4);expect(r.fired.every((s:any)=>s.damage===12)).toBe(true);}else expect(r.zones).toEqual(kind==='siege-mech'?[5.5,5.5]:[7,7]);
});

test('all bosses aim their light gun from its muzzle and sustain fire during heavy attacks',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const rows=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};return ['rail','missile','walker','helicopter','spider','laser','quad-mech','siege-mech','missile-truck'].map(kind=>{g.start(0);g.world.covers=[];g.enemies=[];const b=g.makeUnit(0,0,'boss',kind);g.enemies=[b];b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,28);g.bosses.update(g,b,.01);const s=g.bosses.states.get(b);s.time=100;s.auxTime=0;g.bosses.update(g,b,.01);const shot=g.shots.at(-1),muzzle=b.visual.root.getObjectByName('LightMuzzle'),origin=muzzle.getWorldPosition(b.visual.root.position.clone()),atMuzzle=shot.mesh.position.distanceTo(origin)<.001,light=shot.damage===3;const hp=g.player.hp;for(let n=0;n<100;n++)g.updateShots(1/60);const hit=g.player.hp<hp;g.shots=[];s.phase='charging';s.time=100;g.bosses.update(g,b,1);const charging=g.shots.some((shot:any)=>shot.damage===3);g.shots=[];s.phase='exposed';g.bosses.update(g,b,1);const exposed=g.shots.some((shot:any)=>shot.damage===3);g.shots=[];g.damageUnit(b,999999,g.player.visual.root.position,true);g.bosses.update(g,b,1);return {kind,atMuzzle,light,hit,charging,exposed,dead:g.shots.length===0&&!g.bosses.states.has(b)};});});expect(rows.every((r:any)=>Object.entries(r).every(([key,value])=>key==='kind'||value)),JSON.stringify(rows)).toBe(true);
});

test('secondary rounds respect cover and new bosses appear in campaign finales at every difficulty',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};const counts:any[]=[];for(const difficulty of ['easy','normal','hard','crazy'])for(const stage of [4,10,13]){g.save.difficulty=difficulty;g.start(stage,2);counts.push({difficulty,stage,kind:g.enemies.find((u:any)=>u.role==='boss').bossKind,count:g.enemies.filter((u:any)=>u.role==='boss').length});}
  g.start(0);g.enemies=[];g.world.covers=[];const b=g.makeUnit(0,0,'boss','rail');g.enemies=[b];g.player.visual.root.position.set(0,0,30);const mesh=g.world.clone('steelwall');g.world.covers=[{x:0,z:15,w:10,d:2,hp:Infinity,kind:'steelwall',mesh}];g.bosses.update(g,b,.01);const s=g.bosses.states.get(b);s.time=100;s.auxTime=0;g.bosses.update(g,b,.1);return {counts,cover:g.shots.length===0};
 });expect(r.cover).toBe(true);for(const c of r.counts){expect(c.kind).toBe(({4:'quad-mech',10:'siege-mech',13:'missile-truck'} as any)[c.stage]);expect(c.count).toBe(({easy:1,normal:1,hard:2,crazy:4} as any)[c.difficulty]);}
});

for(const mobile of [false,true])test(`new Blender bosses animate and retain rigs in Low detail on ${mobile?'mobile':'desktop'}`,async({browser})=>{
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1200,height:800},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();
 for(const kind of ['quad-mech','siege-mech','missile-truck']){
  const r=await page.evaluate(async({kind,mobile})=>{const g=(window as any).__steel;g.frame=()=>{};await g.world.load(false);g.world.settings(false);g.start(0);g.world.covers=[];for(const u of g.enemies){u.dead=true;u.visual.root.visible=false;}const b=g.makeUnit(0,0,'boss',kind);g.enemies=[b];b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,14);g.player.hp=g.player.max;g.bosses.update(g,b,.1);const nodeNames=kind==='quad-mech'?['ArmL','ArmR','LeftLeg','RightLeg',...Array.from({length:4},(_,i)=>'GunMuzzle'+i)]:['LauncherL','LauncherR','LaunchMuzzle0','LaunchMuzzle1','LightMuzzle'];const nodes=nodeNames.map(name=>b.visual.root.getObjectByName(name));g.world.scene.fog=null;g.world.camera.position.set(mobile?12:16,mobile?17:16,mobile?25:23);g.world.camera.lookAt(0,2,0);g.world.renderer.render(g.world.scene,g.world.camera);g.updateHud();return {nodes:nodes.every(Boolean),overflow:document.documentElement.scrollWidth>innerWidth,calls:g.world.renderer.info.render.calls,triangles:g.world.renderer.info.render.triangles};},{kind,mobile});expect(r.nodes&&!r.overflow).toBe(true);expect(r.calls).toBeLessThan(1000);await page.screenshot({path:`test-results/new-boss-${kind}-${mobile?'mobile':'desktop'}-detailed.png`});
  const low=await page.evaluate(async()=>{const g=(window as any).__steel,b=g.enemies[0],nodes:any[]=[];b.visual.root.traverse((n:any)=>{if(/^(Arm|LeftLeg|RightLeg|Launcher|LightGun|LightMuzzle|GunMuzzle|LaunchMuzzle)/.test(n.name))nodes.push(n);});const before=nodes.map(n=>[n,n.position.clone(),n.quaternion.clone()]);await g.world.load(true);g.world.settings(true);g.world.renderer.render(g.world.scene,g.world.camera);return {stable:before.every(([n,p,q])=>b.visual.root.getObjectByName(n.name)===n&&n.position.equals(p)&&n.quaternion.equals(q)),triangles:g.world.renderer.info.render.triangles};});expect(low.stable).toBe(true);expect(low.triangles).toBeLessThan(r.triangles*.6);await page.screenshot({path:`test-results/new-boss-${kind}-${mobile?'mobile':'desktop'}-low.png`});
 }
 expect(errors).toEqual([]);await context.close();
});

for(const kind of ['siege-mech','missile-truck'])test(`${kind} missiles cover the target, allow a dodge and emit smoke from launch`,async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const rows=await page.evaluate(kind=>{const g=(window as any).__steel;g.frame=()=>{};return ['stay','dodge','shield'].map(action=>{g.start(0);g.world.covers=[];g.enemies=[];const b=g.makeUnit(0,0,'boss',kind);g.enemies=[b];b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,30);g.player.hp=10000;g.bosses.update(g,b,4.1);const s=g.bosses.states.get(b),locked=JSON.stringify(s.targets),hp=g.player.hp;g.trailClock=0;if(action==='dodge')g.player.visual.root.position.x=30;if(action==='shield')g.shieldTime=6;g.bosses.update(g,b,s.time-.01);const warned=g.player.hp===hp,smoke=g.world.fx.particles.some((p:any)=>p.kind==='smoke'),fixed=locked===JSON.stringify(s.targets);g.bosses.update(g,b,.02);return {action,warned,smoke,fixed,hurt:g.player.hp<hp};});},kind);expect(rows.every(r=>r.warned&&r.smoke&&r.fixed)).toBe(true);expect(rows.map(r=>r.hurt)).toEqual([true,false,false]);
});

test('Marshal sustains its machine gun and retains periodic left-hand fire',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.world.covers=[];g.enemies=[];const b=g.makeUnit(0,0,'boss','siege-mech');g.enemies=[b];b.visual.root.position.set(0,0,0);g.player.visual.root.position.set(0,0,28);g.bosses.update(g,b,.01);const s=g.bosses.states.get(b);s.time=100;const names:string[]=[];const round=g.bossRound.bind(g);g.bossRound=(u:any,a:number,d:number,m:string)=>{names.push(m);round(u,a,d,m);};for(let i=0;i<14;i++){s.auxTime=0;g.bosses.update(g,b,.01);}return {names,left:!!b.visual.root.getObjectByName('GunMuzzle0'),right:!!b.visual.root.getObjectByName('LightMuzzle')};});expect(r.names.filter((n:string)=>n==='LightMuzzle')).toHaveLength(14);expect(r.names.filter((n:string)=>n==='GunMuzzle0')).toHaveLength(2);expect(r.left&&r.right).toBe(true);
});
