import {test,expect} from '@playwright/test';
import {freshSave,parseSave,rewardClear,buyWeapon,ownsWeapon} from '../src/three/campaign';
test('weapon purchases preserve old saves and reject duplicate or unaffordable purchases',()=>{
 const old:any=freshSave();delete old.weapons;old.credits=780;const s=parseSave(JSON.stringify(old));expect(s.weapons).toEqual([]);expect(buyWeapon(s,3)).toBe(true);expect(s.credits).toBe(420);expect(buyWeapon(s,3)).toBe(false);expect(buyWeapon(s,4)).toBe(true);expect(buyWeapon(s,2)).toBe(false);expect(buyWeapon(s,99)).toBe(false);expect(s.credits).toBe(0);expect(parseSave(JSON.stringify(s))).toEqual(s);for(let level=0;level<3;level++)rewardClear(s,0,level);expect(ownsWeapon(s,1)).toBe(true);expect(buyWeapon(s,1)).toBe(false);
});
test('stage shop, saved weapons, fresh ammo and boss ending navigation',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();await page.evaluate(()=>{const g=(window as any).__steel;g.save.level=2;g.start(0,2);g.complete();});await page.locator('[data-action=shop]').click();await page.locator('[data-action=buy-weapon][data-value="2"]').click();expect(await page.evaluate(()=>{const g=(window as any).__steel;return g.save.credits===g.stageResult.total-180;})).toBe(true);await expect(page.locator('[data-weapon-card="2"] .eyebrow')).toContainText('OWNED');
 await page.evaluate(()=>{const g=(window as any).__steel;g.save.credits=780;g.showShop();});for(const w of [3,4])await page.locator(`[data-action=buy-weapon][data-value="${w}"]`).click();await page.reload();await page.getByRole('button',{name:'DEPLOY'}).click();expect(await page.evaluate(()=>{const g=(window as any).__steel;return [g.weaponAvailable(2),...g.specialAmmo];})).toEqual([true,12,6,0,0]);
 expect(await page.evaluate(()=>{const g=(window as any).__steel;g.weapon=3;g.shoot(g.player,true);return g.specialAmmo[0];})).toBe(11);
 for(const mission of [5,8]){await page.evaluate(m=>{const g=(window as any).__steel;g.start(m,2);g.complete();},mission);await page.locator('[data-action=shop]').click();await expect(page.getByRole('heading',{name:'Field shop'})).toBeVisible();await page.locator('[data-action=shop-back]').click();await expect(page.getByRole('heading',{name:'Everyone comes home.'})).toBeVisible();}
});
test('phone shop cards are reachable without horizontal overflow',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();await page.goto('/?e2e');await page.locator('[data-action=shop]').tap();await expect(page.getByRole('heading',{name:'Field shop'})).toBeVisible();expect(await page.evaluate(()=>{const e=document.querySelector('#overlay')!;return e.scrollWidth<=e.clientWidth;})).toBe(true);expect(await page.locator('.upgrade-card .upgrade-icon').count()).toBe(14);await page.screenshot({path:'test-results/shop-mobile.png'});await page.locator('[data-action=shop-back]').tap();await expect(page.getByRole('button',{name:'DEPLOY'})).toBeVisible();await context.close();
});
