import {test,expect} from '@playwright/test';
import {freshSave,parseSave} from '../src/three/campaign';
import {buySkin} from '../src/three/skins';
test('skin purchases and old saves preserve credits and ownership',()=>{const old:any=freshSave();delete old.skins;delete old.skin;old.credits=450;const save=parseSave(JSON.stringify(old));expect(save.skins).toEqual(['classic','sunburst']);expect(save.skin).toBe('classic');expect(buySkin(save,'inferno')).toBe(true);expect(save.credits).toBe(0);expect(buySkin(save,'inferno')).toBe(false);expect(buySkin(save,'guardian')).toBe(false);expect(buySkin(save,'missing')).toBe(false);expect(parseSave(JSON.stringify(save)).skin).toBe('inferno');save.skin='unknown';expect(parseSave(JSON.stringify(save)).skin).toBe('classic');});
test('Blender skins equip before deploy, persist and leave enemy materials unchanged',async({page})=>{
 await page.goto('/?e2e');await page.locator('[data-action=hangar]').click();await expect(page.locator('.skin-card')).toHaveCount(5);await page.locator('[data-action=skin-equip][data-value=sunburst]').click();await page.locator('[data-action=shop-back]').click();await page.getByRole('button',{name:'DEPLOY'}).click();const colors=await page.evaluate(()=>{const g=(window as any).__steel;let player='',enemy='';g.player.visual.root.traverse((o:any)=>{if(o.material?.name==='Armor')player=o.material.color.getHexString();});g.enemies[0].visual.root.traverse((o:any)=>{if(o.material?.name==='Armor')enemy=o.material.color.getHexString();});return {player,enemy};});expect(colors).toEqual({player:'ffac24',enemy:'744b41'});await page.reload();await expect(page.locator('[data-action=hangar]')).toBeVisible();expect(await page.evaluate(()=>(window as any).__steel.save.skin)).toBe('sunburst');
 await page.evaluate(()=>{const g=(window as any).__steel;g.save.credits=450;});await page.locator('[data-action=hangar]').click();await page.locator('[data-action=skin-buy][data-value=inferno]').click();await expect(page.locator('[data-value=inferno]')).toHaveText('EQUIPPED');await page.reload();await page.getByRole('button',{name:'DEPLOY'}).click();const stats=await page.evaluate(()=>{const g=(window as any).__steel;g.shoot(g.player,true);const cannon=g.shots.at(-1).damage;g.specialAmmo[1]=1;g.weapon=4;g.reload=0;g.shoot(g.player,true);return {cannon,arc:g.special.arcs[0].damage,credits:g.save.credits};});expect(stats.cannon).toBeCloseTo(50.6);expect(stats.arc).toBeCloseTo(195.5);expect(stats.credits).toBe(0);
});
test('shield and speed bonuses are isolated and materials are reused',async({page})=>{
 await page.goto('/?e2e');await page.getByRole('button',{name:'DEPLOY'}).click();const r=await page.evaluate(()=>{const g=(window as any).__steel;g.frame=()=>{};g.save.skins.push('guardian','volt');g.save.skin='guardian';g.start(0);g.action('shield');const shield=g.shieldTime;const distances=[];for(const skin of ['classic','volt']){g.save.skin=skin;g.start(0);g.player.visual.root.position.set(0,0,10);g.input.move={x:1,z:0};g.updatePlayer(.1);distances.push(g.player.visual.root.position.x);}for(let i=0;i<30;i++)for(const skin of ['classic','sunburst','guardian','inferno','volt'])g.world.applySkin(g.player.visual.root,skin);return {shield,ratio:distances[1]/distances[0],materials:g.world.skinMaterials.size};});expect(r.shield).toBe(4.5);expect(r.ratio).toBeCloseTo(1.18);expect(r.materials).toBeLessThanOrEqual(25);
});
test('phone skin shop shows real Blender previews and readable choices',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();await page.goto('/?e2e');await page.locator('[data-action=hangar]').tap();await expect(page.locator('.skin-card img')).toHaveCount(5);await expect.poll(()=>page.locator('.skin-card img').evaluateAll(imgs=>imgs.every(i=>(i as HTMLImageElement).complete&&(i as HTMLImageElement).naturalWidth>0))).toBe(true);expect(await page.evaluate(()=>{const e=document.querySelector('#overlay')!;return e.scrollWidth<=e.clientWidth;})).toBe(true);await page.screenshot({path:'test-results/skin-shop-mobile.png'});await page.locator('[data-action=skin-equip][data-value=sunburst]').tap();await page.locator('[data-action=shop-back]').tap();await expect(page.getByRole('button',{name:'DEPLOY'})).toBeVisible();await context.close();
});


test('shop touch release cannot activate a link in the replacement menu',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await page.goto('/?e2e');await page.locator('[data-action=hangar]').tap();
 // Deterministically retarget the first native compatibility click, as seen on the slower CI renderer.
 await page.evaluate(()=>{document.querySelector('#overlay')!.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();const link=document.querySelector('a[href="./legacy.html"]')!;(window as any).__retargetAllowed=link.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,detail:1}));},{capture:true,once:true});});
 await page.locator('[data-action=shop-back]').tap();expect(await page.evaluate(()=>(window as any).__retargetAllowed)).toBe(false);await expect(page.getByRole('button',{name:'DEPLOY'})).toBeVisible();
 await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.locator('a[href="./legacy.html"]').focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(/legacy\.html/);await context.close();
});
