import {test,expect} from '@playwright/test';
import {freshSave,parseSave,buyWeapon} from '../src/three/campaign';
test('saved weapon selection migrates and rejects unowned weapons',()=>{const s:any=freshSave();delete s.equippedWeapon;s.credits=1000;expect(parseSave(JSON.stringify(s)).equippedWeapon).toBe(0);s.equippedWeapon=4;expect(parseSave(JSON.stringify(s)).equippedWeapon).toBe(0);expect(buyWeapon(s,3)).toBe(true);expect(parseSave(JSON.stringify(s)).equippedWeapon).toBe(3);});
for(const mobile of [false,true])test(`purchased guns equip and switch through real controls ${mobile?'phone':'desktop'}`,async({browser})=>{
 const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},hasTouch:mobile,isMobile:mobile});const p=await c.newPage();const press=async(selector:string)=>{if(mobile)await p.locator(selector).tap();else await p.locator(selector).click();};
 await p.goto('/?e2e');await expect(p.locator('[data-action=deploy]')).toBeVisible();await p.evaluate(()=>{const g=(window as any).__steel;g.save.credits=1000;g.frame=()=>{};g.world.renderer.render(g.world.scene,g.world.camera);});await press('[data-action=shop]');await press('[data-action=buy-weapon][data-value="2"]');await press('[data-action=buy-weapon][data-value="3"]');await p.reload();await press('[data-action=deploy]');await expect(p.locator('#weapon-label')).toContainText('Pulse laser · 12');await expect(p.locator('.switch-gun-label')).toBeVisible();
 // Fire the purchased laser with input rather than calling the weapon implementation.
 if(mobile){const r=(await p.locator('#aim-pad').boundingBox())!;const cdp=await c.newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:41,x:r.x+r.width/2,y:r.y+8}]});await expect.poll(()=>p.evaluate(()=>(window as any).__steel.specialAmmo[0])).toBeLessThan(12);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 else{await p.keyboard.down('Space');await expect.poll(()=>p.evaluate(()=>(window as any).__steel.specialAmmo[0])).toBeLessThan(12);await p.keyboard.up('Space');}
 if(mobile)await press('#weapon');else await p.keyboard.press('KeyC');await expect(p.locator('#weapon-picker')).toBeVisible();await press('[data-weapon="3"]');await expect(p.locator('#weapon-label')).toContainText('Siege rockets');await p.reload();await press('[data-action=deploy]');await expect(p.locator('#weapon-label')).toContainText('Siege rockets');
 await press('#weapon');await press('[data-weapon="4"]');await expect(p.locator('#weapon-label')).toContainText('Pulse laser · 12');await p.evaluate(()=>{const g=(window as any).__steel;g.specialAmmo[0]=0;g.updateHud();g.frame=()=>{};g.world.renderer.render(g.world.scene,g.world.camera);});await press('#weapon');await expect(p.locator('[data-weapon="4"]')).toBeDisabled();await expect(p.locator('[data-weapon="4"]')).toContainText('Empty');await p.screenshot({path:`test-results/weapon-switch-${mobile?'mobile':'desktop'}.png`});await c.close();
});
