// Generated by Blender: tools/blender/build_skins.py
export const SKIN_PALETTES = {
  "classic": {
    "Armor": "698d82",
    "Trim": "c7e5d3",
    "Gunmetal": "768a85",
    "Signal": "8dffe7",
    "Tracks": "48565a"
  },
  "sunburst": {
    "Armor": "ffac24",
    "Trim": "663dbf",
    "Gunmetal": "624569",
    "Signal": "fff1a6",
    "Tracks": "354052"
  },
  "guardian": {
    "Armor": "167bda",
    "Trim": "e4f5ff",
    "Gunmetal": "325286",
    "Signal": "54ffff",
    "Tracks": "27394c"
  },
  "inferno": {
    "Armor": "e72b53",
    "Trim": "ffc83d",
    "Gunmetal": "532c45",
    "Signal": "ffed95",
    "Tracks": "302737"
  },
  "volt": {
    "Armor": "b5ed21",
    "Trim": "123b55",
    "Gunmetal": "315967",
    "Signal": "65ffff",
    "Tracks": "253b42"
  }
} as const;
