// Generated by Blender: tools/blender/build_skins.py
export const SKIN_PALETTES = {
  "classic": {
    "Armor": "698d82",
    "Trim": "c7e5d3",
    "Gunmetal": "768a85",
    "Signal": "8dffe7",
    "Tracks": "48565a"
  },
  "sunburst": {
    "Armor": "ffac24",
    "Trim": "663dbf",
    "Gunmetal": "624569",
    "Signal": "fff1a6",
    "Tracks": "354052"
  },
  "guardian": {
    "Armor": "167bda",
    "Trim": "e4f5ff",
    "Gunmetal": "325286",
    "Signal": "54ffff",
    "Tracks": "27394c"
  },
  "inferno": {
    "Armor": "e72b53",
    "Trim": "ffc83d",
    "Gunmetal": "532c45",
    "Signal": "ffed95",
    "Tracks": "302737"
  },
  "volt": {
    "Armor": "b5ed21",
    "Trim": "123b55",
    "Gunmetal": "315967",
    "Signal": "65ffff",
    "Tracks": "253b42"
  },
  "comet": {
    "Armor": "ff6729",
    "Trim": "142354",
    "Gunmetal": "435277",
    "Signal": "fff776",
    "Tracks": "253048"
  },
  "sentinel": {
    "Armor": "09dbe3",
    "Trim": "7e27fa",
    "Gunmetal": "42507e",
    "Signal": "fafffb",
    "Tracks": "233342"
  },
  "talon": {
    "Armor": "ffcf18",
    "Trim": "f32a86",
    "Gunmetal": "663c69",
    "Signal": "fffdf2",
    "Tracks": "352b40"
  },
  "nova": {
    "Armor": "9239fa",
    "Trim": "29f8d6",
    "Gunmetal": "543582",
    "Signal": "fff068",
    "Tracks": "302844"
  },
  "prism": {
    "Armor": "ff3493",
    "Trim": "13e7f2",
    "Gunmetal": "49365e",
    "Signal": "fff4a8",
    "Tracks": "302a46"
  },
  "bastion": {
    "Armor": "273a8a",
    "Trim": "80ff98",
    "Gunmetal": "344864",
    "Signal": "44ff81",
    "Tracks": "23303e"
  },
  "sprint": {
    "Armor": "ff982b",
    "Trim": "d6edff",
    "Gunmetal": "314473",
    "Signal": "459bff",
    "Tracks": "293441"
  },
  "lance": {
    "Armor": "20c7cd",
    "Trim": "ffe14b",
    "Gunmetal": "3b425e",
    "Signal": "ff4569",
    "Tracks": "26343e"
  },
  "quartermaster": {
    "Armor": "e8ac24",
    "Trim": "8928e6",
    "Gunmetal": "57406c",
    "Signal": "d06cff",
    "Tracks": "302941"
  }
} as const;
