"""Author tank material variants and lightweight shop previews in Blender."""
import bpy, json, math
from pathlib import Path
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'public'/'skins'; OUT.mkdir(parents=True,exist_ok=True)
SOURCE=ROOT/'assets'/'blender'; SOURCE.mkdir(parents=True,exist_ok=True)
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
bpy.ops.import_scene.gltf(filepath=str(ROOT/'public'/'models'/'tank.glb'))
palettes={
'classic':{'Armor':'698d82','Trim':'c7e5d3','Gunmetal':'768a85','Signal':'8dffe7','Tracks':'48565a'},
'sunburst':{'Armor':'ffac24','Trim':'663dbf','Gunmetal':'624569','Signal':'fff1a6','Tracks':'354052'},
'guardian':{'Armor':'167bda','Trim':'e4f5ff','Gunmetal':'325286','Signal':'54ffff','Tracks':'27394c'},
'inferno':{'Armor':'e72b53','Trim':'ffc83d','Gunmetal':'532c45','Signal':'ffed95','Tracks':'302737'},
'volt':{'Armor':'b5ed21','Trim':'123b55','Gunmetal':'315967','Signal':'65ffff','Tracks':'253b42'}}
def linear(v):return v/12.92 if v<=.04045 else ((v+.055)/1.055)**2.4
bpy.ops.object.camera_add(location=(6,-8,6));camera=bpy.context.object;camera.rotation_euler=(Vector((0,0,1))-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.type='ORTHO';camera.data.ortho_scale=6.2
scene=bpy.context.scene;scene.camera=camera;scene.render.engine='BLENDER_WORKBENCH';scene.render.resolution_x=320;scene.render.resolution_y=256;scene.render.resolution_percentage=100;scene.render.film_transparent=True;scene.render.image_settings.file_format='PNG';scene.view_settings.view_transform='Standard';scene.display.shading.light='STUDIO';scene.display.shading.color_type='MATERIAL';scene.display.shading.show_shadows=True;scene.display.shading.show_cavity=True
for name,palette in palettes.items():
 for material in bpy.data.materials:
  if material.name in palette:
   code=palette[material.name];rgb=tuple(linear(int(code[i:i+2],16)/255) for i in (0,2,4));material.diffuse_color=(*rgb,1)
   if material.use_nodes:
    bs=material.node_tree.nodes.get('Principled BSDF')
    if bs:bs.inputs['Base Color'].default_value=(*rgb,1)
 scene.render.filepath=str(OUT/(name+'.png'));bpy.ops.wm.save_as_mainfile(filepath=str(SOURCE/('skin-'+name+'.blend')));bpy.ops.render.render(write_still=True)
(ROOT/'src'/'three'/'skin-palettes.ts').write_text('// Generated by Blender: tools/blender/build_skins.py\nexport const SKIN_PALETTES = '+json.dumps(palettes,indent=2)+' as const;\n',encoding='utf-8')
